curl -X POST "http://158.160.160.208:8080/process" \
     -H "Content-Type: application/json" \
     -d "{\"maze\":\"30\\n20\\n\
MRGGGGRRRMMMMMMMMRFFWWWRRRMMMM\\n\
W2WGGRGRRRMMMMMMRRFFRWWF4FFRMM\\n\
WWWGGRGGRRWMMMMMRFFFWWWFFFFRRM\\n\
WSWGGGGRRRWRRRRRRFFFFFGGFFFRRR\\n\
SSSSRGGGRRWRGGGGRRRWWWHHHHRHHR\\n\
RSSHHHHWWWWWGGGGRRRWWWHHHHHRRR\\n\
RRGGWFGGRRWWGGGGRRRRWWWGWSSSSR\\n\
RRGGHWGGMRWWWGGGRRRRRRWWWSSSRS\\n\
RRGGHWGGMRWWWWGGRRRRWWWWWGRRRR\\n\
RRRRRRRRRRWRGGGGRRRWRRWWWGRRRR\\n\
WRGGGGRRRRWRG3GGHHRRRRGGGGRRRR\\n\
WRWGGRGHHHRRGHHHRRRRWRGGGGRRRR\\n\
RWGGGRHHHRWRGHHHFFFWWRGGFFFFFF\\n\
RSGGFFFFFFWRGGGGFFFWWRHHFFFWWW\\n\
RRRRRFFFFFFFFFFFFFFWWRHHWWSSSS\\n\
RFFFFFFFFWWWFFFFRRRWWRGGGGWWWS\\n\
RFFFFFFFWWWFFFFFFRRWWRGGGGWWWW\\n\
RRGGHWGGMRWRGGGGRRRGWWGGGGRRRR\\n\
RRGGHWGGMRWRGGGGRRRRWWGGGGRR1R\\n\
RRRRRRRRRRWRGGGGRRRRWWGGGGRRRM\"}"
